//      DATAMEMBERS   


	UInt_t bG_nscE;
	Float_t  bG_scE[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscEt;
	Float_t  bG_scEt[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscRawE;
	Float_t  bG_scRawE[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscEta;
	Float_t  bG_scEta[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscPhi;
	Float_t  bG_scPhi[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscX;
	Float_t  bG_scX[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscY;
	Float_t  bG_scY[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscZ;
	Float_t  bG_scZ[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscEtaWidth;
	Float_t  bG_scEtaWidth[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscPhiWidth;
	Float_t  bG_scPhiWidth[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscRawEt;
	Float_t  bG_scRawEt[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscMinDrWithGsfElectornSC_;
	Float_t  bG_scMinDrWithGsfElectornSC_[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscFoundGsfMatch_;
	Bool_t  bG_scFoundGsfMatch_[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscE5x5;
	Float_t  bG_scE5x5[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscE2x2Ratio;
	Float_t  bG_scE2x2Ratio[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscE3x3Ratio;
	Float_t  bG_scE3x3Ratio[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscEMaxRatio;
	Float_t  bG_scEMaxRatio[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscE2ndRatio;
	Float_t  bG_scE2ndRatio[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscETopRatio;
	Float_t  bG_scETopRatio[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscERightRatio;
	Float_t  bG_scERightRatio[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscEBottomRatio;
	Float_t  bG_scEBottomRatio[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscELeftRatio;
	Float_t  bG_scELeftRatio[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscE2x5MaxRatio;
	Float_t  bG_scE2x5MaxRatio[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscE2x5TopRatio;
	Float_t  bG_scE2x5TopRatio[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscE2x5RightRatio;
	Float_t  bG_scE2x5RightRatio[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscE2x5BottomRatio;
	Float_t  bG_scE2x5BottomRatio[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscE2x5LeftRatio;
	Float_t  bG_scE2x5LeftRatio[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscSwissCross;
	Float_t  bG_scSwissCross[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscR9;
	Float_t  bG_scR9[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscSigmaIetaIeta;
	Float_t  bG_scSigmaIetaIeta[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscSigmaIetaIphi;
	Float_t  bG_scSigmaIetaIphi[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscSigmaIphiIphi;
	Float_t  bG_scSigmaIphiIphi[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscFull5x5_e5x5;
	Float_t  bG_scFull5x5_e5x5[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscFull5x5_e2x2Ratio;
	Float_t  bG_scFull5x5_e2x2Ratio[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscFull5x5_e3x3Ratio;
	Float_t  bG_scFull5x5_e3x3Ratio[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscFull5x5_eMaxRatio;
	Float_t  bG_scFull5x5_eMaxRatio[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscFull5x5_e2ndRatio;
	Float_t  bG_scFull5x5_e2ndRatio[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscFull5x5_eTopRatio;
	Float_t  bG_scFull5x5_eTopRatio[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscFull5x5_eRightRatio;
	Float_t  bG_scFull5x5_eRightRatio[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscFull5x5_eBottomRatio;
	Float_t  bG_scFull5x5_eBottomRatio[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscFull5x5_eLeftRatio;
	Float_t  bG_scFull5x5_eLeftRatio[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscFull5x5_e2x5MaxRatio;
	Float_t  bG_scFull5x5_e2x5MaxRatio[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscFull5x5_e2x5TopRatio;
	Float_t  bG_scFull5x5_e2x5TopRatio[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscFull5x5_e2x5RightRatio;
	Float_t  bG_scFull5x5_e2x5RightRatio[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscFull5x5_e2x5BottomRatio;
	Float_t  bG_scFull5x5_e2x5BottomRatio[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscFull5x5_e2x5LeftRatio;
	Float_t  bG_scFull5x5_e2x5LeftRatio[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscFull5x5_swissCross;
	Float_t  bG_scFull5x5_swissCross[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscFull5x5_r9;
	Float_t  bG_scFull5x5_r9[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscFull5x5_sigmaIetaIeta;
	Float_t  bG_scFull5x5_sigmaIetaIeta[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscFull5x5_sigmaIetaIphi;
	Float_t  bG_scFull5x5_sigmaIetaIphi[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscFull5x5_sigmaIphiIphi;
	Float_t  bG_scFull5x5_sigmaIphiIphi[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscNHcalRecHitInDIEta5IPhi5;
	Float_t  bG_scNHcalRecHitInDIEta5IPhi5[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscEFromHcalRecHitInDIEta5IPhi5;
	Float_t  bG_scEFromHcalRecHitInDIEta5IPhi5[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscNHcalRecHitInDIEta2IPhi2;
	Float_t  bG_scNHcalRecHitInDIEta2IPhi2[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscEFromHcalRecHitInDIEta2IPhi2;
	Float_t  bG_scEFromHcalRecHitInDIEta2IPhi2[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscPFChIso1;
	Float_t  bG_scPFChIso1[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscPFChIso2;
	Float_t  bG_scPFChIso2[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscPFChIso3;
	Float_t  bG_scPFChIso3[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscPFChIso4;
	Float_t  bG_scPFChIso4[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscPFChIso5;
	Float_t  bG_scPFChIso5[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscPFPhoIso1;
	Float_t  bG_scPFPhoIso1[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscPFPhoIso2;
	Float_t  bG_scPFPhoIso2[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscPFPhoIso3;
	Float_t  bG_scPFPhoIso3[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscPFPhoIso4;
	Float_t  bG_scPFPhoIso4[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscPFPhoIso5;
	Float_t  bG_scPFPhoIso5[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscPFNeuIso1;
	Float_t  bG_scPFNeuIso1[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscPFNeuIso2;
	Float_t  bG_scPFNeuIso2[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscPFNeuIso3;
	Float_t  bG_scPFNeuIso3[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscPFNeuIso4;
	Float_t  bG_scPFNeuIso4[MAX_ARRAY_SIZE] ;
	UInt_t bG_nscPFNeuIso5;
	Float_t  bG_scPFNeuIso5[MAX_ARRAY_SIZE] ;
//      END DATA MEMBERS   

